# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Poland 2014"
email: "devfest2014@gdgpoland.org"
description: "GDG DevFest Poland will be on 8 November in Krakow. 3 parallel tracks & 15 European speakers. You need to be there - save the date!"
baseurl: ""
url: "http://devfest.pl/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55295197-1"
googleAnalyticsSiteUrl: "devfest.pl"

# Organizer Info
organizerName: "GDG Kraków"
organizerAlternateName: "Google Developer Group Kraków"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "devfest2014@gdgpoland.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: ""

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, kraków"
twitterAccount: "@gdgkrk"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/fC9WVQ"
c4sponsorsUrl: "/partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/#location-map", text: "Venue"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
rightNavigationButtons:

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "November 8, 2014"
typeoutTextValues: '"", "Conference", "Workshops", "Poland"'
typeoutFallback: "Conference"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.png", text: "A day full of talks about newest technologies presented by European speakers. There will also be a soft skills set with practical tips & tricks regarding leadership, communication & design." }
 - {title: "Workshops", image: "workshops.png", text: "5 workshops of 1,5 hour each, related to the topics introduced in presentations. That will be a great occasion to try and develop something new using up to date technologies under the supervision of experts." }
 - {title: "Networking", image: "krakow.png", text: "During the conference you will have a lot of occasions to meet interesting people from Poland and Europe. Conference will end with an afterparty in one of Krakow’s clubs." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "18", specialCharacter: "", info: "speakers", detail: "from country and beyond"}
 - {count: "5", specialCharacter: "", info: "workshops", detail: "of pure technologies"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "tech & soft skills"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Collegium Medicum UJ"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "ul. Św. Łazarza 16"
eventAddressLocality: "Kraków"
eventAddressLocalityRegion: "Małopolska"
eventPostalCode: "31-530"
eventAddressCountry: "Poland"
eventStartTime: "2014-11-08T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-08T18:00"
eventPlaceCoordinates: "50.06026420000001, 19.9507287"
mapCenterCoordinates: "50.06026420000001, 19.9507287"
mapMobileCenterCoordinates: "50.061711, 19.950503"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Collegium Medicum UJ"
venueFeatures: ["3 halls", "WiFi for attendees", "Complex Audiovisual System", "Localization in the city center"]

# Tweets Feed Block
tweetsFeedImage: "direction-details.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfestpl"
twitterFeed: "http://kdzwinel.1.ai/tweetledee/searchjson.php"

# Partners Block
organizersTitle: "Organizer"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Regular"
  price: "15"
  priceCurrency: "PLN"
  ticketsNumber: "300"
  ribbon: ""
  buyButtonLink: "http://devfestpl.evenea.pl/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-09-30T00:00"
  validThrough: "2014-11-08T10:00"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDGKrakowPlus", icon: "google-plus"}
 - {link: "https://twitter.com/gdgkrk", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgkrk", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.meetup.com/GDG-Krakow", text: "GDG Krakow Meetup"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:devfest2014@gdgpoland.org", text: "devfest2014@gdgpoland.org"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestpl"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "<p>Google Developer Groups (GDGs) are for developers who are interested in Google's developer technology; everything from the Android, Chrome, Drive, and Google Cloud platforms, to product APIs like the Cast API,Maps API, and YouTube API.</p>

<p>GDG Krakow is fueled by a great group of passionates who actively co-create Krakow’s IT community. We are organizing workshops and meetings dedicated to people fascinated by technologies - mainly IT developers, but also marketers, entrepreneurs and designers.</p>

<p>You can find information about upcoming and past GDG Krakow meetings at <a href='http://www.meetup.com/GDG-Krakow/'>our Meetup page</a>.</p>"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "50.06026420000001, 19.9507287"
logisticsMapMobileCenterCoordinates: "50.06026420000001, 19.9507287"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Kraków"
directionDetailsCards:
 - {title: "Airport", information: 'It takes around 30 minutes to get from the Krakow airport to the city center. It is easily reachable by car, public transport (buses: 292, 902) or taxi. More information is available at <a href="http://www.krakowairport.pl/en/">airport website</a>.'}
 - {title: "Train & Bus Station", information: 'Train & Bus station are both located in the heart of Krakow. The most convenient way to get to the conference place from there is on foot (1,5km, around 15 minutes).'}
 - {title: "Public Transport", information: 'You can download the JakDojade (<a href="https://play.google.com/store/apps/details?id=com.citynav.jakdojade.pl.android&hl=pl">Android</a>, <a href="https://itunes.apple.com/pl/app/jakdojade.pl/id506760190?mt=8">iOS</a>) or MPK Krakow (<a href="https://play.google.com/store/apps/details?id=com.mpk.ideo&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5tcGsuaWRlbyJd">Android</a>, <a href="https://itunes.apple.com/us/app/mpk-krakow-rozk-ad-jazdy/id545233244?mt=8pl">iOS</a>) Apps. Collegium Medicum is located in the city center - the nearest bus & tram stops are: Lubicz, Hala Targowa & Poczta Główna.'}
directionDetailsWideCards: 

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "", image: "hackathon-0.png", details: ""}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: ""}
 - {title: "1nd Place", image: "prize-1.png", info: ""}
 - {title: "3nd Place", image: "prize-3.png", info: ""}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"